# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 16:56
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('DataPublicacao', models.DateField(blank=True, null=True)),
                ('Slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Titulo', unique=True)),
                ('ImagemTopo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('Conteudo', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('Slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Titulo', unique=True)),
                ('NomeMenu', models.CharField(max_length=20)),
                ('MostraMenu', models.BooleanField(default=False)),
                ('ImagemTopo', models.FileField(blank=True, null=True, upload_to=b'')),
                ('Conteudo', tinymce.models.HTMLField(blank=True, null=True)),
                ('RodapePagina', tinymce.models.HTMLField(blank=True, null=True)),
                ('RodapeGeral', tinymce.models.HTMLField(blank=True, null=True)),
                ('Home', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='Pagina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Pagina'),
        ),
    ]
