# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_artigo_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='Detalhavel',
            field=models.BooleanField(default=True),
        ),
    ]
