# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_artigo_detalhavel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='pagina',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
