# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-19 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170919_2204'),
    ]

    operations = [
	    #migrations.RunSQL("update blog_pagina set `order` = id;"),
    ]
